# Generated by Django 2.0.3 on 2022-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0002_auto_20181218_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='count',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
