# Generated by Django 2.0.3 on 2022-03-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_goodsbrowser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsbrowser',
            options={'verbose_name': 'browse history', 'verbose_name_plural': 'browse history'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user information', 'verbose_name_plural': 'user information'},
        ),
        migrations.AlterField(
            model_name='goodsbrowser',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='goods ID'),
        ),
        migrations.AlterField(
            model_name='goodsbrowser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='user ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uaddress',
            field=models.CharField(default='', max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(default='', max_length=11, verbose_name='tel'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='upwd',
            field=models.CharField(max_length=40, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ushou',
            field=models.CharField(default='', max_length=20, verbose_name='delivery address'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uyoubian',
            field=models.CharField(default='', max_length=6, verbose_name='postcode'),
        ),
    ]
